---
- name: Check k3s installation
  hosts: all
  tasks:
    - name: Check if curl is installed
      command: which curl
      changed_when: false

    - name: Check if openssl is installed
      command: which openssl
      changed_when: false

    - name: Check if k3s is installed
      command: which k3s
      changed_when: false
