---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: server
    image: ubuntu-local:20.04
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    cgroupns_mode: private
    override_command: false
    capabilities:
      - SYS_ADMIN
    security_opts:
      - seccomp=unconfined
    tmpfs:
      - /run
      - /tmp
      - /run/lock

  - name: agent
    image: ubuntu-local:20.04
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    cgroupns_mode: private
    override_command: false
    capabilities:
      - SYS_ADMIN
    security_opts:
      - seccomp=unconfined
    tmpfs:
      - /run
      - /tmp
      - /run/lock

provisioner:
  name: ansible
  options:
    skip-tags: modify_cmdline