name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Add local bin to path
      shell: bash
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Test server role
      shell: bash
      run: cd k3s-server && make test

    - name: Test agent role
      shell: bash
      run: cd k3s-agent && make test
